---
title: "Crosse validated model selection for SVM"
author: "Shu Asai"
date: "11/15/2021"
output: pdf_document
indent: true
---


```{r, echo = TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE)
library(tidyverse)  # data manipulation
set.seed(1125)
```


```{r}
da <- readRDS("/home/guest/sem_3/707/health_retirement/processed_001HRS.rds")
summary(da$net_assets)
```



### Table output: 
```{r, echo = FALSE}
options(scipen = 999)
data <- readRDS("~/sem_3/707/health_retirement/model_summary_01.rds")
dat <- data[,c("model","Accuracy", "Sensitivity","Specificity", 
               "Precision", "Kappa")]
rownames(dat) <- NULL
dat <- dat[-which(dat$model == "SVM sigmoid"),]


a <- rank(dat$Accuracy)
b <- rank(dat$Sensitivity)
c <- rank(dat$Specificity)
d <- rank(dat$Precision)
e <- rank(dat$Kappa)
rdat <- data.frame(
  a,b,c,d,e
)

#rowMeans(rdat, na.rm = FALSE, dims = 1)

dat$'Weighted Rank' <- rowMeans(rdat, na.rm = FALSE, dims = 1)
dat <- dat[order(-dat$`Weighted Rank`),]
rownames(dat) <- NULL
```


```{r}
knitr::kable(
  dat,
  digits = 3
)
```

```{r, echo = FALSE}
nd <- readRDS(file = "/home/guest/sem_3/707/health_retirement/scripts/R/deliverable/coef_quantile_reg.rds")
knitr::kable(
  nd,
  digits = 3
)
```

