---
title: "Outlier Analysis"
author: "Shusaku Asai"
date: "11/09/2021"
output: html_document
---

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
options(scipen = 999)
```

```{r, echo=FALSE}
dat <- readRDS("../../../training_001HRS_complete.rds")
```

#### Data Specifications:   
16,309 Observations

### Summary of Net Assets   

```{r, echo = FALSE}
net <- dat$net_assets
summary(net)
```

  

#### Individuals with net assets > $100 million
```{r, echo=TRUE}
length(which(net > 100000000))
```
`r 573/16309` is proportion of individuals with more than $100 million in net assets  



### Top Net Assets   
```{r}
tops <- data.frame(dat[order(-dat$net_assets), "net_assets"])
colnames(tops) <- c("net_assets")
DT::datatable(head(tops,30))
```




### Plots of Net Assets   
  
```{r, echo = FALSE, fig.width=10, fig.height=8}
par(mfrow = c(1,2))
hist(net)
boxplot(net)
```



### Determine variables most correlated for spline:  
```{r}
numdat <- dat[,c("net_assets", "age", "days_in_bed", "children")]
plot(numdat, pch = 16, cex = 0.4)
```

From the correlated scatterplot, we see that days_in_bed may be a good proxy for creating a spline regression.  


