---
title: "Pre-Modeling Analysis"
date: "10/26/2021"
author: ""
output: pdf_document
indent: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE)
library(tidyverse)
library(haven)
library(gbm)
library(kableExtra)
options(scipen=999)
```

#Exploratory Data Analyses    

```{r}
dat <- readRDS("health_retirement/processed_001HRS.rds")
```


### Missing Data Analysis:  
  
```{r}
NAdat <- data.frame(colMeans(is.na(dat)))
NAdat$variable <- rownames(NAdat)
NAdat <- NAdat[order(-NAdat$colMeans.is.na.dat..),]
colnames(NAdat) <- c( "proportion_missing","variable")
rownames(NAdat) <- NULL
knitr::kable(NAdat[,c("variable","proportion_missing")], digits = 3) %>% #invoke kable
  kableExtra::kable_styling(position = "center", full_width = F)
```

### Complete case row proportion:  
  
```{r}
completedat <- dat[complete.cases(dat[,c("retirement", "sex","age","children","marital_status",
                                         "life_satisfaction", "health_rate","high_BP","diabetes",
                                         "cancer","depression","days_in_bed","memory","lonely_pw",
                                         "enjoy_life_pw","job_status","help_friends_py","have_friends",
                                         "difficulty_managing_mny","own_rent_home","social_security",
                                         "medicare","follow_stockmarket","life_insurance",
                                         "net_assets")]),]
nrow(completedat) / nrow(dat)

```
  
  A complete case data set provides ~ 72% of the entire data.  
  We lose ~ 28% of data.  
  